#!/usr/bin/env bash
set -e

gemset_file="$(rbenv-gemset-file 2>/dev/null || true)"

if [ -n "$RBENV_GEMSETS" ]; then
  echo $RBENV_GEMSETS
elif [ -n "$gemset_file" ]; then
  RBENV_GEMSETS=$(cat "$gemset_file")
  if echo $RBENV_GEMSETS | grep -v '\bglobal\b' >/dev/null 2>&1; then
    RBENV_GEMSETS="$RBENV_GEMSETS global"
  fi
  echo $RBENV_GEMSETS
else
  echo "global"
fi


